### ISSUE TITLE
Broken page and tooltip for an item that doesn't exist in 2014

### ISSUE THREAD

**Issue by yuvale** [OpenBudget/open-budget-frontend#180]
![image](https://cloud.githubusercontent.com/assets/2012892/5296951/7c039522-7bb2-11e4-9ace-2ff8f33334f1.png)

This links to a page without data and 'null' in the title ([link](http://www.obudget.org/#budget/3304/2014/main)):
![image](https://cloud.githubusercontent.com/assets/2012892/5297250/9cb253d2-7bb5-11e4-9f99-ca9df4505341.png)

**Comment by yonatann** [comment]
Fixed in commit 690a4a4fe90a9318d1ba4ce03da3719c544ec140
