### ISSUE TITLE
Broken display for items with zero initial allocation

### ISSUE THREAD

**Issue by yuvale** [OpenBudget/open-budget-frontend#181]
![image](https://cloud.githubusercontent.com/assets/2012892/5297289/f0960aa2-7bb5-11e4-9b8a-1ee9dfe965f3.png)

![image](https://cloud.githubusercontent.com/assets/2012892/5297296/02d9f516-7bb6-11e4-94d6-ff2a096c1597.png)

**Comment by orzarchi** [comment]
Hi, I found the bug in another place:
![Bug](http://i.imgur.com/BXs0IzM.png)
The page in question is http://www.obudget.org/#budget/0209/2015/main
