### ISSUE TITLE
Incorporate budget analytics

### ISSUE THREAD

**Issue by jonleary** [OpenBudget/open-budget-frontend#183]
We want to add "kombina detector" features which indicate *interesting* budget sections.
these can be implemented to a document used my economic reporter looking for story ideas, for example.
Indicators such as:
fast-changing sections (extremely large transfers), constant size of section, large gap between allocation and spending, unusual resrve allocation to total allocation ratio.

**Comment by akariv** [comment]
This should be implemented by creating specific re:dash queries which we'll be able to use as sources for tagging budget items / transfers / etc.
