### ISSUE TITLE
Tour updates

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#191]
- [x] open with a popover on one of the bubbles:
- [x] encouraging hover
- [x] telling its story
- [x] proposing to continue the tour
- [x] only closing the popover / tour would prevent its appearance next time
- [x] closing the tour would show a short tooltip under the הדרכה link
- [ ] support custom emphasis on elements in the page (by adding a class to them). For example, make the bubble "breath" when pointed at.

**Comment by yuvale** [comment]
@prsnca will work on this.
@akariv I can't assign to him, does he need to be a member of the group for that?

**Comment by akariv** [comment]
@prnsca was invited to the team, once he accepts you'll be able to assign
to him.

**Comment by yuvale** [comment]
@prsnca Good luck! :)

**Comment by prsnca** [comment]
Thanks, see you next monday :)

@prsnca <https://github.com/prsnca> Good luck! :)

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenBudget/open-budget-frontend/issues/191#issuecomment-72650341>
.
