### ISSUE TITLE
add tabs under graph

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#209]
The tabs would allow to switch the view between:
- detailed transactions (רשימת העברות)
- subsidies (תמיכות)
- tabular data

**Comment by akariv** [comment]
@yonatann Added the tabs, but they need some design love :)

**Comment by mushon** [comment]
Please remove them for now. They break things. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
