### ISSUE TITLE
Enter new government to spreadsheet

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#232]
We need to enter the roles for the new (20th) Gov't and the new finance committee chairman (Gafni)

**Comment by mushon** [comment]
@akariv [this file](https://docs.google.com/spreadsheets/d/1kgLCrrFy9tv4igZO2t_6cxIaVSexspCla63Y0qvQPOM/edit#gid=0) is titled "no longer relevant". If this is not the right place to enter this data where is the right file?

**Comment by akariv** [comment]
This is the correct one:
https://docs.google.com/spreadsheets/d/19HOiE3lMQiINuA1CO2neobpSomYdbObfaSmCM_MoftU/edit#gid=0

The old one may contain data that needs to be moved there (but in a more strict format): 
https://docs.google.com/spreadsheets/d/1kgLCrrFy9tv4igZO2t_6cxIaVSexspCla63Y0qvQPOM/edit#gid=4
