### ISSUE TITLE
Search results do not correlate with suggestion

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#235]
![uploads/1e2973ac-80e6-4d32-a505-3a7dba83a493/9T0zfZJ3Pc.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1e2973ac-80e6-4d32-a505-3a7dba83a493%2F9T0zfZJ3Pc.gif)

Why does the search offer one item title and the page I get give me another?
@akariv might have a clue too.

(This is following a question from Tomer Avital)

**Comment by yonatann** [comment]
@akariv I think that perhaps the indexing was not updated with the new tokenization.
If you give me access to the production app engine application console I can check.

**Comment by akariv** [comment]
I'm guessing that what's happening is that we find a budget item that was relevant before 2014, but we open the same budget code for 2014 - which has a different title.
We should probably open the correct year instead of 2014.

**Comment by yonatann** [comment]
I'll take a look into that.
However, what i'm referring to has to do with the fact that it takes a whole word to get a suggestion instead of a partial match.

**Comment by akariv** [comment]
true, I'll try to update the index to make sure.
