### ISSUE TITLE
When you move from "everything" to "break by clauses" It's not working

### ISSUE THREAD

**Issue by yaronelh** [OpenBudget/open-budget-frontend#251]
I didn't want to open an issue for each one, because I'm not sure that it's not repeating an already open bug

Issues encountered
1.  Moving within the menu "everything" to "break by clauses" It's not working
2. This week in the budget, menu item doesn't work (links to http://www.obudget.org/email/)
3.
הצעת תקציב 2015
ביחס לתקציב 2014
בתחילת השנה / אחרי העברות

You probably know that but these also don't work although they are acting as active links.

4. רזרבות תמיד מופיעות כ 0 יכול להיות זה בכלל לא באג

Surfed around and that's what I came across, 

BTW, I think this is an awesome project
Was anything interesting found using? or is it still in its initial stages?

**Comment by akariv** [comment]
Thanks :)

1. Fixed
2. Still under development
3. Yes, if you hover enough on them it'll tell you why it's not working (I agree that the UX could be better)
4. Reserves are usually 0 at the end of the year (which is the figure we're showing)

Lots of interesting stuff was found! would you like to join us? theres's a lot of interesting stuff to do (not just for programmers).

**Comment by yaronelh** [comment]
It's such an interesting project, I would love to help.
But I'm not sure that I have more than a couple of hours each week

Tell me what you have on the table, and I'll see if I can lend a hand

I'm not a programmer, I'm a UX/UI Designer (Freelancer)

**Comment by akariv** [comment]
A couple of hours a week is what most of us have...
If you're around Tel-Aviv, it would be great to meet you in person (we're meeting every Monday evening in Google Campus TLV - Yigal Alon 98). If this doesn't work for you, we can also work offline.

**Comment by yaronelh** [comment]
I don't know how much time I'll have
Let's start small and go from there, I'll help with what I can.

I'm based in Rama gan, but monday is my busiest day, maybe I can drop in occasionally
in general I'll be happy to help

**Comment by mushon** [comment]
Great, we would love to have you :)

**Comment by yaronelh** [comment]
Thanks Mushon,Adam 
I think you're doing an amazing job. When you're ready, drop me a line about the specifics.
