### ISSUE TITLE
implement back arrow from focus

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#276]
Use Font-Awesome with unicode: ``&#xf060;``

add two 6px by 6px circles

color: #ccc

![uploads/54c1821d-f21d-4ac8-a5f5-58b483a1c68d/obudget-back-arrow.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F54c1821d-f21d-4ac8-a5f5-58b483a1c68d%2Fobudget-back-arrow.png)

**Comment by mushon** [comment]
Turn items for text elements to html elements with ``.main-vis-back-button``, ``.main-vis-zoom-button`` classes (which are already ready with css classes). 
Or implement directly as SVG, the files are available in app/styles/assets

**Comment by nirbadt** [comment]
@alon7786 - Showstopper for launching 2015 budget proposition version - After zooming into a bubble, the button presenting the aggregate over time is missing - the button was last seen wearing grey outline, pointing down. Reward to anyone providing information of the whereabout of ms. button

**Comment by mushon** [comment]
@alon7786 @nirbadt this is actually fixed in master.
Reassigning to @akariv to deploy
