### ISSUE TITLE
עדכון יום/שבוע/חודש אחרון- 

### ISSUE THREAD

**Issue by saaralonbarkat** [OpenBudget/open-budget-frontend#277]
כרגע בחירה ב"יום אחרון" (שהיא ברירת המחדל) מראה את העדכונים שהlast_update שלהם הוא אתמול. במקרה שבו המערכת לא עדכנה אתמול עדכונים הוא לא מראה עדכונים בכלל. (זה מה שהוא מראה עכשיו, בשעה 8:00). 

מציע לפתור את זה על ידי כך שאם אין עדכונים אתמול אז הוא יציג את העדכונים מהיום האחרון שזמין במערכת. 

בנוסף, צריך שאיפשהו ברשימת העדכונים מצד ימין יופיע לגבי כל התקשרות תאריך העדכון שלה (last_update) (זה לא במוקאפ של אורי אבל צריך להכניס את זה)

**Comment by Bnaya** [comment]
Is it still relevant?

**Comment by saaralonbarkat** [comment]
After giving a second thought - I think that the options should be:
היום / אתמול / שבוע אחרון / חודש אחרון

**Comment by Bnaya** [comment]
So we want to add another timeframe option, "yesterday"
What about the other things? now that the default is last week.

**Comment by saaralonbarkat** [comment]
think we can drop the other things. Instead, there will be 4 period
options, as following:

היום
אתמול
שבוע אחרון
חודש אחרון

@uri - is that ok with you?

**Comment by Bnaya** [comment]
@MaaikeB Do you wanna try this one next Monday if we don't make progress with the search till then?

**Comment by MaaikeB** [comment]
@Bnaya sure will do it. 
just where does it appear exactly? maybe can u make a screenshot?

**Comment by Bnaya** [comment]
done by @MaaikeB
