### ISSUE TITLE
Redesign Faceted Search

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#279]

**Comment by mushon** [comment]
התחלה טובה, כמה הערות:
בראשית היתה תיבת טקסט (עם פלייסהולדר בתוכה)
וילחץ היוזר על התיבה - ויופיעו הפילטרים
ויקליד - ויופיעו התוצאות
וילחץ על פילטר, ויסוננו התוצאות, ויופיעו הפילטרים הנוספים
אני לא בטוח שתוצאות החיפוש החופשי יופיעו מיד (מבחינה טכנית, שווה לבדוק) בכל מקרה שווה אולי להציג פרומפט שמדרבן את היוזר ללחוץ Enter או על כפתור החיפוש כדי למצוא את התוצאות האחרות
לא עמותה, ארגון. משרד = סעיף דו ספרתי, אני לא בטוח שאלה פילטרים שונים, לפחות לא ברמה הראשונית. ברמה השניה אולי זה יכול להיות דרופדאון של משרדים ואולי גם דרופדאון של קבוצות נושא (אגרגטים)
מקווה שאת חשה בטוב יותר,
ברכות,
מושון

...
בראשית היתה תיבת חיפוש:
![ii_14f3cbc8fa47c7d0](https://cloud.githubusercontent.com/assets/27123/10434308/5e91c012-7121-11e5-8f75-2fec0fd29786.png)

ובמקביל יופיעו תוצאות המתאימות לחיפוש כשלא מופעלים פילטרים:
![ii_14f3cc1960ea1023](https://cloud.githubusercontent.com/assets/27123/10434402/f933f324-7121-11e5-926f-d62f5b799016.png)


וילחץ היוזר על אחד הפילטרים, ויתעדכנו התוצאות בהתאם.

וילחץ היוזר על אחד הפילטרים ״פטור ממכרז״, ״תמיכה״ או ״העברה״, ויתווסף פילטר נוסף המאפשר לבחור טווח זמנים:
![ii_14f3ccf42003c852](https://cloud.githubusercontent.com/assets/27123/10434408/ff32a612-7121-11e5-9aba-5e584cd17ff5.png)


וילחץ היוזר על התיבה ויקליד.
ויפתחו הפילטרים הבאים:
![ii_14f3cca4f9139a18](https://cloud.githubusercontent.com/assets/27123/10434417/0570cf4a-7122-11e5-8459-b324e8ee9a3e.png)

**Comment by lichen-dagan** [comment]
...

**Comment by mushon** [comment]
בקיצור ליחן, אם תעשי בזה קצת סדר יכול להיות שנוכל לקדם את זה בהאקתון @lichen-dagan

**Comment by mushon** [comment]
התחלה טובה, כמה הערות:
בראשית היתה תיבת טקסט (עם פלייסהולדר בתוכה)
וילחץ היוזר על התיבה - ויופיעו הפילטרים
ויקליד - ויופיעו התוצאות
וילחץ על פילטר, ויסוננו התוצאות, ויופיעו הפילטרים הנוספים
אני לא בטוח שתוצאות החיפוש החופשי יופיעו מיד (מבחינה טכנית, שווה לבדוק) בכל מקרה שווה אולי להציג פרומפט שמדרבן את היוזר ללחוץ Enter או על כפתור החיפוש כדי למצוא את התוצאות האחרות
לא עמותה, ארגון. משרד = סעיף דו ספרתי, אני לא בטוח שאלה פילטרים שונים, לפחות לא ברמה הראשונית. ברמה השניה אולי זה יכול להיות דרופדאון של משרדים ואולי גם דרופדאון של קבוצות נושא (אגרגטים)
מקווה שאת חשה בטוב יותר,
ברכות,
מושון

**Comment by mushon** [comment]
@eladdo92 @yuval-bichler

**Comment by mushon** [comment]
current mockup, @lichen-dagan please expand upon it
![uploads/912f9bc7-73aa-4a54-83e4-d83437b63750/search1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F912f9bc7-73aa-4a54-83e4-d83437b63750%2Fsearch1.png)

**Comment by mushon** [comment]
@lichen-dagan please post link to the Axure prototype here

**Comment by lichen-dagan** [comment]
Search spec:

User enters Obudget landing page:

![uploads/aee19424-0b92-4cc0-9a39-879cb863e43c/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faee19424-0b92-4cc0-9a39-879cb863e43c%2Fblob)

Users clicks the search box, search page appears:
(can return to the last page before entering the search page by clicking X next to the search box)

![uploads/eefbdb4f-0a79-4ef6-9499-4865335f685d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feefbdb4f-0a79-4ef6-9499-4865335f685d%2Fblob)

The user can either enter text to the search box or use the filters:

- Categories: 
הכל / סעיף תקציבי / ארגון / העברה תקציבית / תמיכה ממשלתית / פטור ממכרז
Each category has (number of results) next to its name.
Selected mode = bold text. User selects the category by clicking it.
Default display, when there is no text in the search box: none of the categories are selected. "All" cannot be selected when there is no text in the search box.
Default display, when there is text in the search box: category הכל is selected.

- Date range:
Droplist with the following options:
7 ימים אחרונים (default)
30 ימים אחרונים
השנה התקציבית
הכל
בחירת טווח זמנים (with a calendar, opens when the user clicks this options)

Left to the droplist, there is a timeline showing the following:
- for "last 7 days": value for each day
- for "last 30 days": value for each day
- for "this year": value for each month
- for "all": value for each year
- for custom: value for each year if the selection has multiple years, month if less than a year and multiple months, days if less than a month.
* The edges of the timeline are slideable and the user can reduce the time range by moving them.

![uploads/ac1d76c5-0def-494a-8994-df3e69b6e91b/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fac1d76c5-0def-494a-8994-df3e69b6e91b%2Fblob)

![uploads/503393da-16c8-4532-a9a3-0f27431a69fb/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F503393da-16c8-4532-a9a3-0f27431a69fb%2Fblob)

![uploads/3ab7f76b-bf00-4569-ac21-3f1063bcb75a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3ab7f76b-bf00-4569-ac21-3f1063bcb75a%2Fblob)

Back to the user's filtering options:

When the user clicks one of the categories and there is no text in the search box (all categories can be selected but "all"), all the items in the selected category in the selected time range (last 7 days by default) will appear in the results.
The title above the results will be:
כל ה<שם קטגוריה> ב<טווח זמנים>
Example - selection of
העברות תקציביות + הכל:: 

![uploads/9512c122-40c7-48ae-9a72-8400d9150f79/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9512c122-40c7-48ae-9a72-8400d9150f79%2Fblob)

**Comment by mushon** [comment]
Made some progress on the design:

![uploads/be97582f-fecb-47a5-ba66-0d162f3b7040/search2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe97582f-fecb-47a5-ba66-0d162f3b7040%2Fsearch2.png)

**Comment by nirbadt** [comment]
יחידת תוצאת חיפוש: 
:התקשרות בפטור  ממכרז



![uploads/361b8bb4-1dd0-49a0-ab46-f98706effc88/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F361b8bb4-1dd0-49a0-ab46-f98706effc88%2Fblob)


* תאריך: 

תאריך עדכון /
תחילת ההתקשרות /
 תחילת ההתקשרות - סיום ההתקשרות

צריך להחליט מה מהם הכי חשוב ומתאים להכלל באובייקט תוצאת החיפוש.

**Comment by mushon** [comment]
סעיפים: 
![uploads/ab228d48-713b-480c-aa17-c89fd1332138/search_items.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab228d48-713b-480c-aa17-c89fd1332138%2Fsearch_items.png)

העברות: 
![uploads/0b24e34d-6f8e-401e-a2cb-0b1c7545fe92/search_transfers.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0b24e34d-6f8e-401e-a2cb-0b1c7545fe92%2Fsearch_transfers.png)

פטורים: 
![uploads/9f2915d6-56fd-4256-9b88-621da83e38bf/search_tenders.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9f2915d6-56fd-4256-9b88-621da83e38bf%2Fsearch_tenders.png)

תמיכות: 
![uploads/08e366e0-98c3-4e2c-a400-31a21324f219/search_grants.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F08e366e0-98c3-4e2c-a400-31a21324f219%2Fsearch_grants.png)

**Comment by lichen-dagan** [comment]
דוגמא לתצוגה של הקטגוריה "הכל" :

![image](https://cloud.githubusercontent.com/assets/13319518/13227748/df33e258-d9a0-11e5-8831-5716041c3d40.png)

@mushon 
אנחנו צריכים להחליט אם פילטר הזמן יופיע כאן או לא.

**Comment by mushon** [comment]
@lichen-dagan I think we should so we can have a quick overview of a certain time span of activity

**Comment by mushon** [comment]
![search_all](https://cloud.githubusercontent.com/assets/27123/13233658/5b7a8c42-d9bd-11e5-90a1-fea60dcbea3c.png)
![search_items](https://cloud.githubusercontent.com/assets/27123/13233661/5b9cb376-d9bd-11e5-8699-61ae5f45dcb6.png)
![search_exempt](https://cloud.githubusercontent.com/assets/27123/13233659/5b7ae660-d9bd-11e5-9ef3-7719ac2e1094.png)
![search_grants](https://cloud.githubusercontent.com/assets/27123/13233660/5b9bd60e-d9bd-11e5-9692-df37ef36467a.png)
![search_transfers](https://cloud.githubusercontent.com/assets/27123/13233662/5bb16ce4-d9bd-11e5-8b32-ec946caa3183.png)

**Comment by lichen-dagan** [comment]
@mushon 
please frame the 
"מטרות"
in the 
תמיכות
objects, just like the free texts in
פטורים, העברות.
thanks!

**Comment by lichen-dagan** [comment]
@mushon 
also, in the category 
הכל
there are only
סעיפים, תמיכות

while we agreed that
הכל
will contain all the categories, even if they're empty.

**if it's just for the design - forget it.

**Comment by lichen-dagan** [comment]
@mushon 
also, in the 
העברות
i dont think we should have both the icon and the stamp.

**Comment by lichen-dagan** [comment]
@mushon 
also, we agreed that the amounts of money will be black and the change (%) will only color the signs (arrows for סעיף , +- for העברה).

the color won't be so noticeable on the minus (-) though.... but we can figure it out.

**Comment by lichen-dagan** [comment]
result object of ארגון:

![image](https://cloud.githubusercontent.com/assets/13319518/13580802/797c0122-e4ac-11e5-9ead-317dac757af6.png)

under the org name there will be the org type. in the example above the type is "private company", can be also 
עמותה רשומה,
חברה לתועלת הציבור
etc.

**Comment by mushon** [comment]
@lichen-dagan 
latest designs:

![uploads/fb879fac-9441-458d-b37b-2f97faced9e5/search_all.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffb879fac-9441-458d-b37b-2f97faced9e5%2Fsearch_all.png)

![uploads/0e514f8b-95bf-4935-8c87-4acb84a871db/search_items.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0e514f8b-95bf-4935-8c87-4acb84a871db%2Fsearch_items.png)

![uploads/a2997fcf-2b3e-4c5f-a51e-a5823e74bfcb/search_transfers.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa2997fcf-2b3e-4c5f-a51e-a5823e74bfcb%2Fsearch_transfers.png)

![uploads/b71feffa-5eeb-4e33-b8e6-3e02ff12e099/search_grants.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb71feffa-5eeb-4e33-b8e6-3e02ff12e099%2Fsearch_grants.png)

![uploads/055218ab-0592-438b-a612-5570e2c1a741/search_exempt.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F055218ab-0592-438b-a612-5570e2c1a741%2Fsearch_exempt.png)

**Comment by mushon** [comment]
Added the design for the orgs @lichen-dagan please review:
![search_orgs](https://cloud.githubusercontent.com/assets/27123/14086812/c599ea2c-f52f-11e5-8cb5-d24c907a205e.png)

**Comment by Bnaya** [comment]
@MaaikeB

**Comment by mushon** [comment]
@uripaz9 will start working on the html/css markup w00t!!!

**Comment by mushon** [comment]
link to the design mockup on Invision:
https://invis.io/MV7UO5T95#/162439872_Search_All

**Comment by mushon** [comment]
Marketch for inspecting the design:
[obudget.org-search.zip](https://github.com/OpenBudget/open-budget-frontend/files/346776/obudget.org-search.zip)

**Comment by akariv** [comment]
This issue was moved to OpenBudget/budgetkey-app-search#1
