### ISSUE TITLE
Implement a Jekyll blog

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#280]
- install a [Jekyll blog](http://jekyllrb.com/) on a new repo
- implement the design from the obudget.org website to make the blog feel "at home"
- tie the blog into the obudget.org site

**Comment by mushon** [comment]
@yochaico

**Comment by mushon** [comment]
@yochayco check this

**Comment by paperboydesignlab** [comment]
Status update 14:10.
Downloading Xampp and Github failed due to extremely poor wifi performance. 

Will attempt again once reaching normal connection speeds.
Will update.

@mushon @yochayco

**Comment by paperboydesignlab** [comment]
Error cloning Jekyll-Bootstrap to my git repository, any ideas?

@mushon 

![image](https://cloud.githubusercontent.com/assets/15155676/10557557/4edd05c2-74ba-11e5-8838-a54be612431b.png)

**Comment by mushon** [comment]
@akariv

**Comment by akariv** [comment]
You probably didn't set up your ssh keys correctly...

See here instructions: https://help.github.com/articles/generating-ssh-keys/#platform-windows

**Comment by paperboydesignlab** [comment]
Fixed. 

This is the Rep for the blog's dev version:
https://paperboydesignlab.github.io/ 

Will update later today

**Comment by akariv** [comment]
cool :)

**Comment by paperboydesignlab** [comment]
Silly question - How do I find Jekyll's local directory (The one that is served).
There's a bunch of folders called Jekyll, which one is the one where the layout and themes are?

**Comment by paperboydesignlab** [comment]
never mind, figured it out

**Comment by paperboydesignlab** [comment]
Hi

I'm having trouble with a couple of issues:
(1) implementing Alef
(2) RTL

**Comment by mushon** [comment]
Please refer to the guide for implementing Alef here:
http://alef.hagilda.com

As for RTL, what are the problems you're running into?
Maybe something like this automatic css RTLer could help:
http://cssjanus.commoner.com/
Here's another one that I just found but never tried:
https://github.com/MohammadYounes/rtlcss#install

**Comment by mushon** [comment]
Since you're using Bootstrap, you might also want to use Bootstrap RTL, which could do the trick even better: https://github.com/morteza/bootstrap-rtl

**Comment by paperboydesignlab** [comment]
Issues that still need to be resolved:

1. RTL
2. Title baseline height
3. Header font styles
4. Link font styles
5. Post font styles
6. Sponsored - wtf get it OFF GET IT OFF
7. Removing Top Bar links
8. Remove copyright footer

Let me know if you see anything else

**Comment by nirbadt** [comment]
Moved to next tasks - not a showstopper for launch of new budget

**Comment by Bnaya** [comment]
@mushon can it be considerd as done?

**Comment by mushon** [comment]
Yes
