### ISSUE TITLE
איחוד של "משרד הבינוי" ו"משרד הבינוי והשיכון"

### ISSUE THREAD

**Issue by saaralonbarkat** [OpenBudget/open-budget-frontend#283]
יש לאחד את שמות המשרדים בדיבי. 

בכל הרשומות שבהן מצויין "משרד הבינוי והשיכון" יש לשנות ל"משרד הבינוי" (השם החדש).

**Comment by nirbadt** [comment]
@mushon if an office changes its name how do we deal with it?

**Comment by mushon** [comment]
We should think of a strategy for addressing this. For example - start maintaining aliases. @akariv what do you think?

**Comment by Bnaya** [comment]
We have a fix for this on the client side for the exemptions,
Dose the budget visualization also have that issue?

**Comment by akariv** [comment]
The issue as far as I understand is only w/ publishers in the exemption
table.
