### ISSUE TITLE
transitional budget misrepresentation

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#290]
Transitional budgets are set by their previous year's updated budget (after transactions). However this is not how they are represented on the site. Please fix:

![uploads/0f3cd283-c1b0-4a7c-8326-542086d81537/misrepresenting_trans-budgets.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0f3cd283-c1b0-4a7c-8326-542086d81537%2Fmisrepresenting_trans-budgets.png)

**Comment by nirbadt** [comment]
@mushon showstopper?

**Comment by mushon** [comment]
Yes it is, but it looks fixed. Closing.
<img width="341" alt="continuous_budget" src="https://cloud.githubusercontent.com/assets/27123/11047820/00426b42-873d-11e5-8e80-ef0c9162d49c.png">
