### ISSUE TITLE
Gafni appears too soon on the timeline

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#298]
This is probably a content bug. But I'm not sure… @akariv?

![uploads/bab13ae9-3947-4f04-acbf-0edf9ccf8186/gafni.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbab13ae9-3947-4f04-acbf-0edf9ccf8186%2Fgafni.png)

**Comment by akariv** [comment]
Will be resolved in the next few hours
