### ISSUE TITLE
exemptions with unknown volume (סכום לא ידוע(

### ISSUE THREAD

**Issue by saaralonbarkat** [OpenBudget/open-budget-frontend#308]
בממשק הגרפי  יש לרשום "סכום לא ידוע" רק ברשומות שבהן סטאטוס ההחלטה הוא "טרום החלטת וועדה". 
אחרת, אם סכום = 0 או 1, ועילת הפטור היא התקשרות המשך, יש לרשום "על חשבון התקשרות קודמת".

Write "unknown volume" only in exemptions where decision = 'טרום החלטת ועדה'
Otherwise, if volume =0 or 1, and regulation like '%התקשרות המשך%' then write "על חשבון התקשרות קודמת". @Bnaya

**Comment by naamac** [comment]
ready waiting for #325

**Comment by naamac** [comment]
@Bnaya i think this was merged.

**Comment by Bnaya** [comment]
It was mereg accidently and reverted,
The exception refactor branch is now at @uripaz9 hands for the design
