### ISSUE TITLE
share link to "specific exemption view" 

### ISSUE THREAD

**Issue by saaralonbarkat** [OpenBudget/open-budget-frontend#314]
In the "exemptions updates page" (http://staging.open-budget-il.appspot.com/#spending///), for each exemption there should be an option to share link of the specific exemption view (i.e. the view of the supplier page, when the specific exemption is open). the share botton should be right to the supplier_id (which is on the top left side).

This will enable to share not only the supplier page but also the page with the view of the specific exemption. 

@Bnaya @uripaz9  @naamac

**Comment by Bnaya** [comment]
Got it, this is called "Permalink"
It can be based on http://staging.open-budget-il.appspot.com/#entity/930029053/2007/ page

**Comment by Bnaya** [comment]
@saaralonbarkat Where do we want the link to be and how's the icon should looks like?

**Comment by saaralonbarkat** [comment]
היי אורי - תוכל לעזור לנו בזה?

**Comment by saaralonbarkat** [comment]
I think there should be a "share" icon, a bit right to the "supplier
number". +uripaz9@gmail.com <uripaz9@gmail.com> what do you think?

**Comment by akariv** [comment]
We need to design a standalone exemption page, which is where this
permalink should point.

בתאריך שבת, 14 בנוב׳ 2015, 17:03 מאת saaralonbarkat <
notifications@github.com>:

**Comment by Bnaya** [comment]
I think http://staging.open-budget-il.appspot.com/#entity/930029053/2007/  + autoselect the relavent exemption can do it

**Comment by akariv** [comment]
How can you select the relevant exemption? What if there are 10 exemptions
for that entity for that year?
