### ISSUE TITLE
add multiple selection filter of publishers and sort option to exemption update

### ISSUE THREAD

**Issue by saaralonbarkat** [OpenBudget/open-budget-frontend#319]
The recent exemption page should implement a sort and a multiple selection of publishers without requesting each selection from the API.
In order for this feature to be implemented in the client side all the data from the selected dates range should be loaded to the client. The limit sent to the API request should be 10,000.

The multiple select field (סנן משרדים) should be placed to the right of the dates range field. When clicked it should open a multiple selection list of all the publishers with an option to select all which is the default. When multiple offices have been selected the field should indicate so with the text "בחירה מרובה".

The sort field (מיין לפי) should be placed to the left of the dates range field. The sort options are: total flags (עניין), volume (סכום), update date (תאריך). The default is total flags. When sorting by volume, the records without a volume should be treated as 0. @Bnaya @naamac

**Comment by Bnaya** [comment]
@uripaz9

**Comment by Bnaya** [comment]
http://obudget.bnaya.net/#spending//2014/main
@saaralonbarkat  see my progress

**Comment by uripaz9** [comment]
Cool,

I didn't understand the sorting according "עיניין".

Is it possible to present in the checklist of the ministries the number of connections of each office depending on the length of time the user has chosen?

**Comment by saaralonbarkat** [comment]
That's aussome! +Omer Bartal <omerbartal@gmail.com>

Is there a mutiple choice option for the offices?

**Comment by saaralonbarkat** [comment]
and one more thing - we need to fix the המשרד לביטחון פנים.

this name should include the following:
המשרד לבטחון פנים
המשרד לביטחון פנים
המשרד לבטחון פנים - שירות בתי הסוהר
המשרד לביטחון פנים - משטרת ישראל
המשרד לביטחון פנים - נציבות כבאות והצלה

**Comment by Bnaya** [comment]
@uripaz9 we have internal heuristic "score" for each exemption
I guess we should add few words about it some where. we call it "עניין" for now
Saar can tell more about it

About the number in the ministries list, its a comlication i want to avoid this moment and need to think if its makes sense 

@saaralonbarkat  About the free text search, currently it do nothing. is it needed? on which fields there is might be keywords we would want to search in?

**Comment by saaralonbarkat** [comment]
I think that the free text search is redundant in the updates page. (There
will certinly be a free text search in the search page which we will
develop in the future. Theoretically we can search the following fields:
Supplier, description, reason, subject).

What about the multiple selection?

**Comment by Bnaya** [comment]
The multiple selection should be available
