### ISSUE TITLE
check empty response for entity_id=590000931

### ISSUE THREAD

**Issue by naamac** [OpenBudget/open-budget-frontend#320]
check empty response for entity_id=590000931exemption_id=571776

**Comment by Bnaya** [comment]
Any conclusions? maybe we should add a message on the client side

**Comment by naamac** [comment]
at the moment i didn't find this exemption in our d.b and the gov.il d.b. If we see another instance-we'll start debugging it.

**Comment by Bnaya** [comment]
Found another one,
http://www.obudget.org/api/entity/589104751
http://www.obudget.org/api/exemption/publication/571867
