### ISSUE TITLE
fork bootstrap-rtl to apply bootstrap-rtl.less.patch (?)

### ISSUE THREAD

**Issue by Bnaya** [OpenBudget/open-budget-frontend#333]
Is there any technical reason we don't fork bootstrap-rtl to apply our path in the fork instead after bower install?
@akariv @mushon

**Comment by mushon** [comment]
Not that I know of. Adam?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by akariv** [comment]
No reason.
