### ISSUE TITLE
git submodules

### ISSUE THREAD

**Issue by Bnaya** [OpenBudget/open-budget-frontend#334]
Can we ditch the git submodules in favor of  install them via npm/bower?

@akariv

**Comment by akariv** [comment]
Yes

**Comment by Bnaya** [comment]
@akariv do you wanna fork 
https://github.com/yonatann/interval-query.git
&
https://github.com/morteza/bootstrap-rtl
To be under OpenBudget organization ?

**Comment by akariv** [comment]
Done
