### ISSUE TITLE
404 for url in Calcalist article

### ISSUE THREAD

**Issue by SonOfLilit** [OpenBudget/open-budget-frontend#338]
http://www.calcalist.co.il/local/articles/0,7340,L-3621262,00.html links to http://the.open-budget.org.il/report/app/#203804/2013, better solve it with them or quicker - set up a redirect.

**Comment by akariv** [comment]
@SonOfLilit This is on purpose - they posted a link to a development server without consulting with us and we took the server down.
BTW it was back in 2014 (over two years ago), I doubt if this interests anyone now.
