### ISSUE TITLE
Tour redirects to 2014 urls

### ISSUE THREAD

**Issue by Bnaya** [OpenBudget/open-budget-frontend#367]
The tour data
http://www.obudget.org/api/training/main
redirects to 2014 urls,
we need do make it year agnostic (?) 
Lets remove the 2014/main part and add the current year dynamically

**Comment by Bnaya** [comment]
@akariv where we can edit this data?

**Comment by akariv** [comment]
I changed it, it should propagate to the website in a couple of hours.

Adam
