### ISSUE TITLE
The Guide's pop-ups appear in English instead of Hebrew when coming back to the website directly from the Blog

### ISSUE THREAD

**Issue by feltfire** [OpenBudget/open-budget-frontend#369]
1. Paste http://www.obudget.org/ in your address field
    ==> The Guide's pop-up window appears in Hebrew like in this screenshot:
![image](https://cloud.githubusercontent.com/assets/17835292/13759137/8d65e886-ea35-11e5-8043-25749d622a68.png)

2. Click the link "הבלוג שלנו" (our blog) at the top of the page
3. Click the link "לאתר מפתח התקציב" (Back to the Budget key) at the top of the page
(Sometimes it doesn't show up immediately, and we need to click the "הדרכה" link.
    ==> The Guide's pop-up window appears in English like in this screenshot :
![image](https://cloud.githubusercontent.com/assets/17835292/13759243/14a79d80-ea36-11e5-8f36-40895b8f427e.png)

4. Click 'Next' in the pop-up itself -> the guide's next pop-ups are all in English
5. **not a mandatory step** Click the 'X' at the corner of the pop-up -> The temporary pop-up (reminding you to click the "הדרכה" Link when you need it) appears in Hebrew, like so:
![image](https://cloud.githubusercontent.com/assets/17835292/13759487/1e6e2478-ea37-11e5-90e3-98fff4c70ca9.png)

6. Click the main logo "מפתח התקציב" in order to refresh the page 
   ==> The Guide's pop-up window appears in Hebrew again, like so:
![image](https://cloud.githubusercontent.com/assets/17835292/13759536/57c4b250-ea37-11e5-916f-23b6c8c8dd62.png)

7. Done. 

Found using Chrome Version 48.0.2564.116 m :)

**Comment by Bnaya** [comment]
The link in the blog to the website contains redundant params,
ill removed them
