### ISSUE TITLE
Add JSON, CSV & html table links from every page

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#71]
- budget
- transactions
- entity
- exemption

**Comment by mushon** [comment]
This is basically just a button to download the relevant data in every data-driven end page. It's a simple standalone task. @yaronelh want to take on this?

**Comment by yaronelh** [comment]
Haven't exactly understood what  you need, you need a button?

**Comment by mushon** [comment]
yes, it's a simple task to identify when, where, in what form would users be interested in getting the raw data for what they're currently looking at and how would that look, considering their expectations and the fact we're using multiple sources. @akariv feel free to add your thoughts.

**Comment by yaronelh** [comment]
Can you give me more of the context, Where? Is it across the application?

**Comment by akariv** [comment]
Each page in the site is based upon one or more data-sets.
Each data set can be downloaded in various formats (CSV,Excel,JSON,HTML
etc.)
We want a consistent look and feel for giving the user a way to download
the raw, source data, which will be intuitive and with a small footprint.

For example, in the budget timeline page, we have these data sets:
 - Budget history (yearly sums: approved, revised, used)
 - Budget approval dates
 - Timeline data (i.e. the people bar below)
 - Budget Changes (sums, dates, explanations...)
 - Supports
 - Spending (exemption data)

We don't want to throw 4 buttons at every spot in the page, so it'll have
to be a little more complex than just a button.

(Again, it's just a little something to get us started, there are more
heavy tasks down the road :) )

**Comment by yaronelh** [comment]
Okay, just to make sure I'm getting it right for example this page
Is comprised from one or more data sets and you want a way to download all the information currently displayed to multiple file formats

http://www.obudget.org/g2/bl/4505#budget/4505/2014/main

yes?

**Comment by mushon** [comment]
Yes, and a part of the job is to decide whether to do it on a page basis, on a component basis or what…

**Comment by yaronelh** [comment]
Okay I'll think about how to solve it

**Comment by yaronelh** [comment]
My suggestion is below, 

Side note, this actually emphasizes again the problem with the amount of colors in the interface.

![1](https://cloud.githubusercontent.com/assets/7690499/8765000/2f402cf8-2e01-11e5-85fa-3d48598f2f4c.png)

**Comment by mushon** [comment]
אני לא בטוח שזה הכיוון.
המיקום לא מסביר לי מה ייוצא לקובץ? הסכום הכולל? וגם למה לאפשר את היצוא של הסעיפים האחרים אם אנחנו בסעיף ספציפי? זה גם מייצר מקצב שמאוד מקשה על זיהוי הלינק וגם פוגע בתשומת הלב לסכום שקודם הופיעה באופן עצמאי. המיקום הזה גם בעייתי כי הוא יקר לנו במובייל.
מעבר לזה, אנחנו רוצים לאפשר יצוא הן של השינויים לאורך זמן והן של נושאים אחרים שמופיעים בטאבים למטה.
כמו כן, לאחר הלחיצה, מה מתקבל? קובץ? איזה פורמט? או האם זה תיבת דיאלוג שמאפשרת לי בחירה? באיזו דרך?

מקווה שהשאלות יעזרו לדייק. אתה שוב מוזמן להצטרף למפגש הפיתוח השבועי מחר מ-18:00 עד השעות הקטנות. אנחנו לרוב מגיעים באיזור 19:00.

מושון
On July 19, 2015 at 10:32:36 AM, yaronelh (notifications@github.com) wrote:

My suggestion is below,

Side note, this actually emphasizes again the problem with the amount of colors in the interface.

**Comment by yaronelh** [comment]
Hi Mushon

אני לא בטוח שזה הכיוון. > Don't worry about it :)  It's just a proposed option 

Most of the things you mentioned are solvable, since the idea was to make it a drop-down
But there were several points of information I wasn't aware of, first that the site can function in a Mobile environment which is surprising due to the amount of information presented. And the second one that there would be variations in a time and subjects options to the Tabs at the bottom (I still need to understand what you mean by that)

Well it's not that a simple of a task, it requires prior knowledge and a complete understanding of the task.

Anyway I'll see if I can jump in tomorrow,

**Comment by yaronelh** [comment]
Hi Mushon

It didn't work out for me, to come to the meeting
Maybe next week

btw, Is it an open complex or you need some kind of the authorization to enter?

Cheers
Yaron

**Comment by daonb** [comment]
I want to take this.  To keep things simple, I want to add a download button the the left of the search icon. Clicking the button will download a zip file with CSV files containing all the data we have relating to the page.
